### ISSUE TITLE
Empty commits

### ISSUE THREAD

**Issue by Zwyx** [estruyf/estruyf#1]
Hey, I took from you the idea of using a GitHub Action to auto-update my ReadMe, it's great ;-) I wanted to let you know that you can use the parameter [`empty-commits: false`](https://github.com/JasonEtco/rss-to-readme#empty-commits-default-true) in order to not have thousands of empty commits in your repo.
Cheers

**Comment by estruyf** [comment]
Oh, that is great to know! Thanks for letting me know, will do the change   😄

**Comment by estruyf** [comment]
Updated!
